"""empty message

Revision ID: 007f26f2fb6c
Revises: 46ec103a3469
Create Date: 2023-08-22 10:27:45.187251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007f26f2fb6c'
down_revision = '46ec103a3469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('File', sa.Column('headers', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('File', 'headers')
    # ### end Alembic commands ###
