"""empty message

Revision ID: 77780bf5f269
Revises: 007f26f2fb6c
Create Date: 2023-08-22 17:59:29.785403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77780bf5f269'
down_revision = '007f26f2fb6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('File',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('extension', sa.String(length=5), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('headers', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_index(op.f('ix_File_name'), 'File', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_File_name'), table_name='File')
    op.drop_table('File')
    # ### end Alembic commands ###
